hlwm: Reorder config and remove unnecessary keybindings

diff --git a/config/herbstluftwm/autostart b/config/herbstluftwm/autostart
--- a/config/herbstluftwm/autostart
+++ b/config/herbstluftwm/autostart
@@ -9,35 +9,41 @@ hc emit_hook reload
 fgColor=$_xrdb_color4 # blue
 bgColor=$_xrdb_background # black
 
-tags="I:1 II:2 III:3 IV:4 V:5 VI:6 VII:7 VIII:8 IX:9 X:0 XI:bracketleft XII:bracketright"
-hc rename default "I" || true
-
-# set wm name to LG3D to fix Java issues
-hc set wmname LG3D
-
-# remove all existing keybindings
-hc keyunbind --all
+# cleanup old sessions
+hc keyunbind   --all
+hc mouseunbind --all
+hc unrule      --all
 
 # keybindings
-# if you have a super key you will be much happier with Mod set to Mod4
 #Mod=Mod1    # Use alt as the main modifier
 Mod=Mod4   # Use the super key as the main modifier
 
-hc keybind $Mod-q spawn slock
+tags="I:1 II:2 III:3 IV:4 V:5 VI:6 VII:7 VIII:8 IX:9 X:0 XI:bracketleft XII:bracketright"
+hc rename default "I" || true
+key_index=0
+for tag in $tags; do
+	IFS=':' read -r name key <<EOF
+$tag
+EOF
+	hc add "$name"
+	if ! [ -z "$key" ]; then
+		hc keybind $Mod-$key       use_index  "$key_index"
+		hc keybind $Mod-Shift-$key move_index "$key_index"
+	fi
+	((key_index=key_index+1))
+done
+
 #hc keybind $Mod-Shift-q quit
 hc keybind $Mod-Shift-r reload
-hc keybind $Mod-Shift-q close_or_remove
 
 # applications
 hc keybind $Mod-o spawn dmenu_run -sb "$fgColor" -sf "$bgColor"
 hc keybind $Mod-Shift-o spawn passmenu -sb "$fgColor" -sf "$bgColor"
-
+hc keybind $Mod-Escape spawn slock
 hc keybind $Mod-Return spawn ${TERMINAL:-st}
 hc keybind $Mod-e spawn pcmanfm
 
 # extra keys
-#hc keybind XF86MonBrightnessDown spawn xbacklight -dec 5 -time 500
-#hc keybind XF86MonBrightnessUp spawn xbacklight -inc 5 -time 500
 hc keybind XF86AudioPlay spawn media-ctl.sh play
 hc keybind XF86AudioPrev spawn media-ctl.sh prev
 hc keybind XF86AudioNext spawn media-ctl.sh next
@@ -46,7 +52,6 @@ hc keybind XF86AudioRaiseVolume spawn volume-adjust.sh up
 hc keybind XF86AudioMute spawn volume-adjust.sh mute
 hc keybind $Mod-XF86AudioMute spawn pavucontrol
 hc keybind $Mod-F1 spawn monitor-toggle.sh # XF86Display
-hc keybind $Mod-F2 spawn network-restart.sh
 hc keybind XF86TouchpadToggle spawn touchpad-toggle.sh
 
 # basic movement
@@ -61,78 +66,63 @@ hc keybind $Mod-k     focus up
 hc keybind $Mod-l     focus right
 
 # moving clients
-hc keybind $Mod-Shift-Left  shift left
-hc keybind $Mod-Shift-Down  shift down
-hc keybind $Mod-Shift-Up    shift up
-hc keybind $Mod-Shift-Right shift right
 hc keybind $Mod-Shift-h     shift left
 hc keybind $Mod-Shift-j     shift down
 hc keybind $Mod-Shift-k     shift up
 hc keybind $Mod-Shift-l     shift right
+hc keybind $Mod-Shift-Left  shift left
+hc keybind $Mod-Shift-Down  shift down
+hc keybind $Mod-Shift-Up    shift up
+hc keybind $Mod-Shift-Right shift right
 
-# splitting frames
 # create an empty frame at the specified direction
-hc keybind $Mod-z       split   vertical 0.5
-hc keybind $Mod-v       split   horizontal 0.5
+hc keybind $Mod-z split vertical   0.5
+hc keybind $Mod-v split horizontal 0.5
 # let the current frame explode into subframes
-hc keybind $Mod-Control-space split explode
+hc keybind $Mod-Ctrl-space split explode
 
 # resizing frames
 resizestep_large=0.05
 resizestep_small=0.01
-hc keybind $Mod-Control-h       resize left +$resizestep_small
-hc keybind $Mod-Control-j       resize down +$resizestep_small
-hc keybind $Mod-Control-k       resize up +$resizestep_small
-hc keybind $Mod-Control-l       resize right +$resizestep_small
-hc keybind $Mod-Control-Left    resize left +$resizestep_large
-hc keybind $Mod-Control-Down    resize down +$resizestep_large
-hc keybind $Mod-Control-Up      resize up +$resizestep_large
-hc keybind $Mod-Control-Right   resize right +$resizestep_large
+hc keybind $Mod-Ctrl-h     resize left  +$resizestep_small
+hc keybind $Mod-Ctrl-j     resize down  +$resizestep_small
+hc keybind $Mod-Ctrl-k     resize up    +$resizestep_small
+hc keybind $Mod-Ctrl-l     resize right +$resizestep_small
+hc keybind $Mod-Ctrl-Left  resize left  +$resizestep_large
+hc keybind $Mod-Ctrl-Down  resize down  +$resizestep_large
+hc keybind $Mod-Ctrl-Up    resize up    +$resizestep_large
+hc keybind $Mod-Ctrl-Right resize right +$resizestep_large
 
-key_index=0
-for tag in $tags; do
-	IFS=':' read -r name key <<EOF
-$tag
-EOF
-	hc add "$name"
-	if ! [ -z "$key" ]; then
-		hc keybind $Mod-$key       use_index  "$key_index"
-		hc keybind $Mod-Shift-$key move_index "$key_index"
-	fi
-	((key_index=key_index+1))
-done
-
-# cycle through tags
-hc keybind $Mod-Escape           use_previous
 hc keybind $Mod-BackSpace        use_previous
 hc keybind $Mod-quoteleft        use_index  +1 --skip-visible
-hc keybind $Mod-period           use_index  +1 --skip-visible
 hc keybind $Mod-Shift-quoteleft  use_index  -1 --skip-visible
+hc keybind $Mod-period           use_index  +1 --skip-visible
 hc keybind $Mod-comma            use_index  -1 --skip-visible
 hc keybind $Mod-Shift-period     move_index +1 --skip-visible
 hc keybind $Mod-Shift-comma      move_index -1 --skip-visible
-hc keybind $Mod-Shift-apostrophe shift_to_monitor +1
+hc keybind $Mod-Shift-apostrophe      shift_to_monitor +1
+hc keybind $Mod-Shift-Ctrl-apostrophe shift_to_monitor -1
+
+# focus
+hc keybind $Mod-apostrophe      cycle_monitor +1
+hc keybind $Mod-Ctrl-apostrophe cycle_monitor -1
+hc keybind $Mod-Tab             cycle_all +1
+hc keybind $Mod-Shift-Tab       cycle_all -1
+hc keybind $Mod-c               cycle
+hc keybind $Mod-i               jumpto urgent
 
 # layouting
-hc keybind $Mod-r remove
-#hc keybind $Mod-s floating   toggle
-hc keybind $Mod-f fullscreen toggle
-hc keybind $Mod-p pseudotile toggle
-hc keybind $Mod-space cycle_layout 1
+hc keybind $Mod-f       fullscreen   toggle
+#hc keybind $Mod-p       pseudotile   toggle
+hc keybind $Mod-Shift-q close_or_remove
+hc keybind $Mod-r       remove
+#hc keybind $Mod-s       floating     toggle
+hc keybind $Mod-space   cycle_layout +1
 
 # mouse
-hc mouseunbind --all
 #hc mousebind $Mod-Button1 move
 #hc mousebind $Mod-Button2 zoom
 #hc mousebind $Mod-Button3 resize
-
-# focus
-hc keybind $Mod-Shift-Escape cycle_monitor
-hc keybind $Mod-apostrophe   cycle_monitor
-hc keybind $Mod-Tab          cycle_all +1
-hc keybind $Mod-Shift-Tab    cycle_all -1
-hc keybind $Mod-c            cycle
-hc keybind $Mod-i            jumpto urgent
 
 # theme
 hc attr theme.tiling.reset 1
@@ -154,8 +144,6 @@ hc attr theme.inner_width 0 # no inner border
 hc attr theme.outer_width 0 # no outer border
 
 hc attr theme.active.color $fgColor
-hc attr theme.floating.border_width 5 # display a small border of
-hc attr theme.floating.outer_width 1 # white around floating windows
 hc attr theme.normal.color ${_xrdb_color20:-$_xrdb_color12} # grey (256 vs reg)
 hc attr theme.urgent.color $_xrdb_color1 # red
 
@@ -165,31 +153,29 @@ hc set smart_window_surroundings 0
 hc set smart_frame_surroundings 1
 hc set mouse_recenter_gap 0
 
+hc set tree_style '╾│ ├└╼─┐'
+hc set wmname LG3D # fix Java issues
+hc set auto_detect_monitors 1
+
 # rules
-hc unrule -F
 hc rule focus=off # normally do not focus new clients
 hc rule class~'(Pinentry)' focus=on
 hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
 hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
 hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
 
-# unlock, just to be sure
-hc unlock
+hc unlock # unlock, just to be sure
 
-hc set tree_style '╾│ ├└╼─┐'
-
-# do multi monitor setup here, e.g.:
+# monitor setup
 # hc set_monitors 1280x1024+0+0 1280x1024+1280+0
-# or simply:
-hc detect_monitors
+hc detect_monitors # automatic detection
 
-# load background
+# load random background
 feh --no-fehbg --randomize --recursive --bg-scale "${XDG_DATA_HOME:-$HOME/.local/share}/feh"
 
 # find the panel
 panel=${XDG_CONFIG_HOME:-$HOME/.config}/herbstluftwm/panel.sh
 [ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
 for monitor in $(hc list_monitors | cut -d: -f1); do
-	# start it on each monitor
-	"$panel" $monitor &
+	"$panel" $monitor & # start panel on each monitor
 done
